service: sls-todo

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: "dev"
  region: "us-east-1"
  memorySize: 512
  timeout: 30
  stackTags:
    name: ${self:service}
    createdby: kowsik
    owner: Harini
  environment:
    TODOS_TABLE: Todos-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3003
  dynamodb:
    start:
      port: 5000
      inMemory: true
      migrate: true
    stages:
      - dev
# plugin to run it locally
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-plugin-resource-tagging
  - serverless-offline

# lambda functions
functions:
  createTodo:
    handler: src/api/createTodo.handler
    events:
      - http:
          path: create-todo
          method: POST
          cors: true
  getAllTodos:
    handler: src/api/getAllTodos.handler
    events:
      - http:
          path: get-todos
          method: GET
          cors: true
  getTodo:
    handler: src/api/getTodo.handler
    events:
      - http:
          method: get
          path: get-todo/{todoId}
          cors: true
  updateTodo:
    handler: src/api/updateTodo.handler
    events:
      - http:
          method: put
          path: update-todo/{todoId}
          cors: true
  deleteTodo:
    handler: src/api/deleteTodo.handler
    events:
      - http:
          method: delete
          path: delete-todo/{todoId}
          cors: true

resources:
  Resources:
    TodoListTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        AttributeDefinitions:
          - AttributeName: todoId
            AttributeType: S
        KeySchema:
          - AttributeName: todoId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1